services:
  postgres_db:
    image: postgres:16
    container_name: bookstore_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bookstore_db_user -d bookstore_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bookstore_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - "./app:/app/app"
    depends_on:
      postgres_db:
        condition: service_healthy
    command: >
      sh -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'

volumes:
  postgres_data:

